zoho/clone/urls.py
### Local Imports
# View Class
from clone.views import (
   LoginView,
   CreateLeaveView,
   TimeTrackerView,
   AttendenceView
)

# View Function 
from clone.views import (
   self_service,
   leave_tracker,
   home,
   daily_log,
   attendence_data
)

# Django Imports
from django.urls import path


app_name = 'zoho'

urlpatterns = [
   path('',LoginView.as_view(),name="main"),    
   path('home/',home,name='home'),
   path('self/',self_service,name="self"),
   path('login/',LoginView.as_view(),name="login"),
   path('leave-tracker/',leave_tracker,name="leaver-tracker"),
   path('apply-leave/',CreateLeaveView.as_view(),name="apply-leave"),
   path('time-tracker/',TimeTrackerView.as_view(),name="time-tracker"),
   path('daily-log/',daily_log,name="daily-log"),
   path('attendence/',AttendenceView.as_view(),name="attendence"), # POST
   path('attendence/data/listview/',AttendenceView.as_view(),name='attendence-list-view'),
   path('attendence-by-date/',attendence_data,name="attendence-by-date")

]

zoho/zoho/urls.py
from django.contrib import admin
from django.urls import path,include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('clone.urls')),
    path('__debug__/',include(debug_toolbar.urls)),
]

zoho/clone/models.py
# Django
from django.db import models
# from django.db.models.signals import post_save
# from django.dispatch import receiver
from django.contrib.auth.models import User

# Local imports
from .services.choices import (
   martial_status,
   positions,
   emp_type,
   off_loc,
   emp_status,
   genders,
   working_status,
   hiring_sources,
   leave_type
)


# def create_hrm(instance,**kwargs):
#    """Function will create a new HRM id of new joinee

#       Foramt: department id + month of join + employee id 
#    Args:
#        instance (_type_): instance of newly created record
#    """
#    dept_id = instance.dept.id
#    join_month = instance.joining_date.strftime('%m')
#    emp_id = instance.id
#    hrm_id = "HRM{}{}{}".format(dept_id,join_month,emp_id)
#    return hrm_id

class Department(models.Model):
   name = models.CharField(max_length=255,null=False,blank=True)
   emp_cnt = models.IntegerField(null=False,blank=False,default=0) 

   def __str__(self):
      return self.name

class EmpPersonal(models.Model):
   """
      Class stores all the personal data of the employee
   """
   user = models.ForeignKey(User,on_delete=models.CASCADE)
   no = models.CharField(max_length=10,null=False,blank=True)
   email=models.EmailField(max_length=254,help_text='Employee personal email id',null=False,blank=True)
   birth_date = models.DateField()
   martial_status = models.CharField(max_length=100,choices=martial_status)
   communication_add = models.TextField()
   permanent_add = models.TextField()
   postal_code = models.CharField(max_length=6,null=False,blank=True)
   pan_no = models.CharField(max_length=11,null=False,blank=True)
   aadhar_no = models.CharField(max_length=20,null=False,blank=True)
   gender = models.CharField(max_length=10,null=False,blank=True,choices=genders)
   hiring_src = models.CharField(max_length=100,null=False,blank=True,choices=hiring_sources)

   def str(self):
      return self.user.username
   
class EmpSelf(models.Model):
   """
      Class contains all the employee data in one class.
   """
   user = models.ForeignKey(User,related_name="employee_id",on_delete=models.CASCADE)
   dept = models.ForeignKey(Department,on_delete=models.CASCADE)
   rm = models.ForeignKey(User,related_name='reporting_manager_id',on_delete=models.CASCADE)
   personal = models.ForeignKey(EmpPersonal,related_name='personal_data',on_delete=models.CASCADE,null=True,help_text="Employee Personal Data")
   # hrm_id = models.CharField(max_length=100,null=False,blank=True)
   office_loc = models.CharField(max_length=255,default='jaipur',choices=off_loc)
   position = models.CharField(max_length=255,choices=positions)
   type = models.CharField(max_length=255,choices=emp_type)
   status = models.CharField(max_length=100,choices=emp_status)
   joining_date = models.DateTimeField()
   working_status = models.CharField(max_length=100,null=False,blank=True,choices=working_status)

   class Meta:
      verbose_name_plural = 'employee info'

class LeaveType(models.Model):
   name = models.CharField(max_length=255,help_text="Leave name",choices = leave_type,unique=True)
   timestamp = models.DateTimeField()

   class Meta:
      verbose_name_plural = 'Leave Type'

   def str(self):
      return self.name

class LeavesCreateModel(models.Model):
   """
   Whenever user apply for the leave the details will be recorded in this model.
   """
   title = models.CharField(max_length=100,null=True,blank=True)
   leave_type = models.ForeignKey(LeaveType,on_delete=models.CASCADE)
   cnt_leave = models.IntegerField(null=False,default=0)
   from_date = models.DateField()
   to_date = models.DateField()
   reason = models.TextField(max_length=500)

   class Meta:
      verbose_name_plural = 'Create Leave'

   def save(self,*args,**kwargs):
      self.cnt_leave = count_leave_days(self)
      return super(LeavesCreateModel,self).save(**kwargs)

class LeavesAndHolidays(models.Model):
   """
   This model will record all the leave details of user.
   The records in this table will be inserted by the admin of the zoho.
      As admin has the right to decide the available paid leaves to the employee.
   """
   user = models.ForeignKey(User,on_delete=models.CASCADE)
   leave_id = models.ForeignKey(LeavesCreateModel,on_delete=models.CASCADE,null=True,blank=True)
   curr_avail_paid_leave  = models.IntegerField(help_text="Currently available paid leaves",default=0,null=False)
   curr_booked_paid_leave = models.IntegerField(help_text="Currently booked paid leave",default=0,null=False) 
   curr_booked_unpaid_leave = models.IntegerField("Currently booked unpaid leave",default=0,null=False)
   is_leave_approved = models.BooleanField(help_text="Set to True whenever Reporting manager of the employee approve the leave. By default it is True",default=False)
   
   class Meta:
      verbose_name_plural = "Leaves and Holiday"

   
class TimeTracker(models.Model):
   date = models.DateField()
   user = models.ForeignKey(User,on_delete=models.CASCADE)
   jobs = models.JSONField()
   ttl_hours = models.CharField(max_length = 50,null=False,blank=True)

class Attendence(models.Model):
   user = models.ForeignKey(User,on_delete=models.CASCADE)
   date = models.DateField(auto_now=False,null=False)
   
   class Meta:
      indexes = [
         models.Index(fields = ['date'])
      ]
      verbose_name_plural = 'attendence'

   def __str__(self):
      return str(self.date)

class DailyAttendenceRecords(models.Model):
   attendence = models.ForeignKey(Attendence,on_delete=models.CASCADE)
   check_in = models.TimeField(auto_now=False,auto_now_add=False)
   check_out = models.TimeField(auto_now=False,auto_now_add=False,null=True,blank=True)
   total_hours = models.TimeField(auto_now=False,auto_now_add=False,null=True)
   status = models.BooleanField(help_text='user is active or not')
   
   
######## Function & Signals

def count_leave_days(instance):
   from_day,from_month = int(instance.from_date.strftime("%d")),int(instance.from_date.strftime("%m"))
   to_day,to_month = int(instance.to_date.strftime("%d")),int(instance.from_date.strftime("%m"))
   if from_month == to_month:
      diff = to_day - from_day
   else:
      pass
   return (diff+1)
   

# @receiver(post_save,sender=EmpSelf)
# def process_emp(sender,instance,created,**kwargs):
#    if created:
#       hrm_id = create_hrm(instance)
#       emp_id = instance.id
#       EmpSelf.objects.filter(id = emp_id).update(hrm_id=hrm_id)

      
     

zoho/clone/views.py
# Standard Library
from datetime import ( 
   datetime, 
   timedelta 
)
import datetime as dt
import json  
from sortedcontainers import SortedDict

# Django
from django.shortcuts import render,redirect
from django.http import JsonResponse,HttpResponse
from django.views import View
from django.core import serializers
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required

# Local Imports
from .models import (
   LeaveType as l_type,
   LeavesAndHolidays as leaves_and_holidays
) 
from .services.time_tracker import (
   save_timesheet_data,
   get_all_time_sheet_data,
   get_date_time_log
)
from .services.leave_tracker import apply_leave
from .services.attendence import Attendence
from .services.self_service import emp_self_data
from .services.service_function import get_dates_ranges

@login_required(login_url='/login/')
def home(request):
   return render(request,'home.html')

def self_service(request):
   if request.method == "GET":
      context = emp_self_data(request)
      return render(request,'self.html',context)

def leave_tracker(request):
   get_emp_leave_status = leaves_and_holidays.objects.filter(user=request.user).order_by("-id")[0]
   
   leave_history_data = leaves_and_holidays.objects \
                     .select_related('leave_id') \
                     .filter(user=request.user) \
                     .order_by('-leave_id__from_date','-leave_id__to_date') \
                     .all()

   context = {
      'available_paid_leave' : get_emp_leave_status.curr_avail_paid_leave,
      'booked_paid_leave': get_emp_leave_status.curr_booked_paid_leave,
      'booked_unpaid_leave':get_emp_leave_status.curr_booked_unpaid_leave,
      'all_leave_data': leave_history_data
   }
   return render(request,"leave-tracker.html",context)

def daily_log(request):
   _date = datetime.now().date()
   data = get_date_time_log(request,log_date=_date)
   
   if data is not None:
      context = {
         'time_log_data':data["job_data"],   
         'ttl_work_hrs':data["ttl_work_hours"]
      }   
   else:
      context = {
         'time_log_data':None
      }
   return render(request,'day_log.html',context)

class LoginView(View):
   def get(self,request):
      if request.user.is_authenticated:
         logout(request)
      return render(request,'login.html')

   def post(self, request):
      loginUsername = request.POST.get('username')
      loginPassword =  request.POST.get('password')
      user = authenticate(username=loginUsername, password=loginPassword)
      if user is None:
         return render(request,'login.html',status=401)
      else:
         login(request,user)
         return redirect('zoho:home')

class CreateLeaveView(View):
   
   def get(self, request):
      get_leave_type = l_type.objects.only('name','id')
      context = {
         'leave_type':get_leave_type
      }
      return render(request,'create-leave.html',context)

   def post(self, request):

      # leave create process
      is_leave_created = apply_leave(request)
      print(is_leave_created)
      print("Leave application successful" if is_leave_created else "Leave application failed")    
      return redirect("zoho:leaver-tracker")

class TimeTrackerView(View):
   def get(self, request):
      get_all_time_sheet_data(request)
      return render(request,"time-tracker.html")
      
   def post(self, request):
      timesheet_data = request.POST.get("job_data")
      ttl_work_hr = request.POST.get('ttl_work_hr')
      if timesheet_data != None:
         job_dict = json.loads(timesheet_data)
         if save_timesheet_data(request,job_dict,total_work_hrs = ttl_work_hr):
            print("data created")
            return JsonResponse({
               'recorded':True})

class AttendenceView(View):
   
   def __init__(self) -> None:
      self.attendence = Attendence()

   def post(self,request):
      action = request.POST.get('action')
      if action == 'in':
         data = {
            'date': request.POST.get('date'),
            'checkin': request.POST.get('checkin'),
            'action': action
         }
         is_checked_in = self.attendence.record_checkin(request.user,data)
         return is_checked_in
      else:
         data = {
            'checkout': request.POST.get('checkout'),
            'action':action,
            'record_id':request.POST.get('record_id'),
            'attendence_id':request.POST.get('attendence_id'),
            'ttl_work_hrs':request.POST.get('ttl_work_hrs'),
         }
         is_checked_out = self.attendence.record_checkout(data)
         return is_checked_out
   
   def get(self,request):
      # MONDAY TO SUNDAY
      total_hrs_dict = dict()
      swd = request.GET.get('startWeek',None)
      ewd = request.GET.get('endWeek',None)
      navigation = request.GET.get('nav',None)
      if swd is not None and ewd is not None:
         if navigation == "-1":
            startWeekDate = ( datetime.strptime(swd,"%d-%m-%Y") - timedelta(days = 7) ).date()
            endWeekDate = startWeekDate + timedelta(days = 6)
            
         else:
            startWeekDate = ( datetime.strptime(swd,"%d-%m-%Y") + timedelta(days = 7) ).date()
            endWeekDate = startWeekDate + timedelta(days = 6)
            
      else:
         curr_date = datetime.now().date()
         weekDay = curr_date.weekday()
         startWeekDate = curr_date - timedelta(days = weekDay)
         endWeekDate = startWeekDate + timedelta(days = 6)
         
      _startWeekDate = datetime.strftime(startWeekDate,"%d-%m-%Y")
      _endWeekDate = datetime.strftime(endWeekDate,"%d-%m-%Y")

      date_ranges = get_dates_ranges(startWeekDate)
      weekAttendenceData = self.attendence.get_attendence_by_weak(request.user,_startWeekDate,_endWeekDate) 

      for data in weekAttendenceData:
         date = data.attendence.date
         total_hrs = data.total_hours
         if date in total_hrs_dict.keys():
            hrs = total_hrs_dict[date]["total_hours"]
            total_hrs = (
                  datetime.combine(dt.date(1,1,1),hrs) + timedelta(hours=total_hrs.hour,minutes=total_hrs.minute,seconds=total_hrs.second)).time()

         total_hrs_dict[date] = {
            'total_hours':total_hrs,
            'attendence_id': data.attendence.id,
            'attendence_record_id':data.id 
         }
      
      remaining_dates = (date_ranges - total_hrs_dict.keys())

      final_attendence_data = SortedDict({
            **total_hrs_dict,
            **dict.fromkeys(
                  remaining_dates,{
                     'total_hours':datetime.strptime("00:00:00","%H:%M:%S"),
                     'attendence_id':"",
                     'attendence_record_id':""
                  }
               )
         })
      
      context = {
         'startWeekDate': _startWeekDate,
         'endWeekDate':_endWeekDate, 
         'data_dict':final_attendence_data
      }

      return render(request,"attendence.html",context)

def attendence_data(request):
   attendence = Attendence()
   attendence_id = request.GET.get('attendence_id',None)
   if attendence_id is not None:
      query_set = attendence.get_attendence_by_id(attendence_id)
      return JsonResponse(serializers.serialize('json',query_set),safe=False)
   else:
      return HttpResponse(None,content_type='text/plain')

zoho/clone/templates/attendence.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}


<div class="d-flex flex-column">
   <div class="row">
      <div class="col-2"> 
         {% include 'menu.html' %} 
      </div>
      <div class="col-10">
         <div class="container-fluid">
            <div class="row my-2">
               <div class="col-sm-3"></div>
               <div class="col-sm-6">
                  <nav class="Zinlinenav">
                     <ul class="pager">
                        <li>
                           <a href="{% url 'zoho:attendence-list-view'  %}?startWeek={{startWeekDate}}&endWeek={{endWeekDate}}&nav=-1" >
                              <i class="week-nav fa-solid fa-caret-left"></i>
                           </a>
                        </li>
                        <li>
                           <input type="hidden" id="hidden-time-tracker-startWeekDate" value="{{startWeekDate}}" />
                           <p class="time-tracker-week-dates" id="time-tracker-week-dates"> {{startWeekDate}} &nbsp-&nbsp {{endWeekDate}}  </p>
                           <input type="hidden" id="hidden-time-tracker-endWeekDate" value={{endWeekDate}} />
                        </li>
                        <li>
                           <a href="{% url 'zoho:attendence-list-view'  %}?startWeek={{startWeekDate}}&endWeek={{endWeekDate}}&nav=1" >
                              <i class="week-nav fa-solid fa-caret-right"></i>
                           </a>
                        </li>
                        {% comment %} monday to sunday  {% endcomment %}
                     </ul>
                  </nav>
               </div>
               <div class="col-sm-3"></div>
            </div>
            <div class="show_attendence_data my-1">
               <div class="data-title text-center my-2">Attendence</div>
               <div class="data-body m-4">
                  <div class="d-flex flex-wrap flex-column">
                     <div class="row" id="_attendence_data">
                        {% for key,value in data_dict.items %}
                           {% if key|date:"w" != "0"%}
                              <div class="col-lg-6 col-sm-12 my-2">
                                 <a href="#" style="text-decoration: none;color:black" onclick="get_attendence_by_date({{value.attendence_id}})">
                                    <div class="card">
                                       <div class="card-title p-2 text-center attendence-data-card mb-0">
                                          {{key|date:"l d,Y"}}
                                       </div>
                                       <div class="card-body px-2 py-2">
                                          <div class="row">
                                             <div class="col-12">
                                                <div class="position-relative  text-center" style="font-size:x-small">
                                                   <p class="ttl-work-hrs-box"> 
                                                      <div class="d-flex" style="justify-content:space-between">
                                                         <div class="">Total Hours: {{value.total_hours|time:"H:i:s"}} hrs</div>
                                                         <div class="">
                                                            {% if value.attendence_record_id == "" %}
                                                            <span class="text-danger">Absent</span>
                                                            {% else %}
                                                               <span class="text-success">Present</span>
                                                            {% endif %}
                                                         </div>
                                                      </div>
                                                      <div class="progress-boxes">
                                                         {% if value.attendence_record_id == "" %}
                                                            <div class="progress-volume" style="background:red"></div>
                                                         {% else %}
                                                            <div class="progress-volume" style="background:rgb(31 228 45);"></div>
                                                         {% endif %}
                                                   </div>
                                                   </p>
                                                </div>
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                 </a>
                              </div>
                           {% else %}
                              <div class="col-lg-12 col-sm-12 my-2">
                                 <a href="#" style="text-decoration: none;color:black">
                                    <div class="card">
                                       <div class="card-title p-2 text-center attendence-data-card mb-0">
                                          {{key|date:"l d,Y"}}
                                       </div>
                                       <div class="card-body px-2 py-2" style="background-color:rgb(255 221 221)">
                                          <div class="row">
                                             <div class="col-12">
                                                <div class="position-relative  text-center" style="font-size:x-small">
                                                   <p class="ttl-work-hrs-box"> 
                                                      <div class="d-flex" style="justify-content:space-between">
                                                         <div class="">Total Hours: {{value.total_hours|time:"H:i:s"}} hrs</div>
                                                         <div>Weekend</div>
                                                         </div>
                                                      </div>
                                                      <div class="progress-boxes">
                                                         <div class="progress-volume" style="background-color:rgb(255 153 66)"></div>
                                                   </div>
                                                   </p>
                                                </div>
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                 </a>
                              </div>
                           {% endif %}
                        {% endfor %}
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   {% include 'attendence_data.html' %}
{% endblock content %}

zoho/clone/templates/create-leave.html
{% include 'layout.html' %}
{% load static %}

{% block content %}

<div class="d-flex flex-column">
   <div class="row">
      <div class="col-2"> 
         {% include 'menu.html' %} 
      </div>
      <div class="col-10">
         <div class="leave-tracker p-4" style="background-color: rgb(243 243 243);">
            <div class="d-flex flex-wrap flex-column m-2">
               <div class="create-leave-box p-1" style="background-color:white">
                  <h6>Apply Leave</h6>
                  <div class="leave-form p-2">
                     <form method="post" action="{% url 'zoho:apply-leave' %}">
                        <input type="hidden" value="{{request.user.id}}" name="emp_user_id"/>
                        {% csrf_token %}
                        <div class="form-group row">
                          <label for="leave-type" class="col-sm-2 col-form-label">Leave type</label>
                          <div class="col-sm-10">
                           <select class="form-select form-control" aria-label="Leave type" name="leave_type" required>
                              <option selected>Open this select menu</option>
                              {% for type in  leave_type %}
                                 <option value="{{type.id}}">{{type.name | upper}}</option>
                              {% endfor %}
                            </select>
                          </div>
                        </div>
                        <div class="form-group row" data-provide="datepicker">
                           <label for="" class="col-sm-2 col-form-label">From Date</label>
                           <div class="col-sm-4 form-group row">
                              <input type='date' class="form-control" placeholder="From" name="from-date" required/>
                           </div>
                           <label for="leave-type" class="col-sm-2 col-form-label">To Date</label> 
                           <div class="col-sm-4">
                              <input type='date' class="form-control" placeholder="To" name="to-date" required/>
                           </div>
                        </div>  
                        <div class="form-group row">
                           <label for="leave-type" class="col-sm-2 col-form-label">Reason</label>
                           <div class="col-sm-10">
                              <textarea class="form-control" name="leave-reason" rows="3" placeholder="Reason" maxlength="200" required></textarea>
                           </div>
                        </div>  
                        <div class="form-group row mx-3 my-2">
                           <span class="mx-2">
                              <button class="btn btn-primary" value="create-leave">Apply</button>                              
                           </span>
                           <span class="mx-2">
                              <a href="{% url 'zoho:home' %}" role="button" class="btn btn-outline-dark">Cancel</a>                              
                           </span>
                        </div>
                        <div class="error-message my-3">
                           {% if messages %}
                              
                              <div class="alert alert-warning alert-dismissible fade show w-75" role="alert">
                                 <strong>Holy guacamole!</strong> You should check in on some of those fields below.</strong>
                              </div>
                           {% endif %}
                        </div>
                      </form>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

{% endblock content %}

zoho/clone/templates/home.html
{% extends 'layout.html' %}


{% load static %}
{% block content %}
   {% include 'menu.html' %}
{% endblock content %}

zoho/clone/templates/menu.html
<div class="menu navbar navbar-light bg-dark">
   <div class="container">
     <ul class="nav nav-pills">
      
      <li class="nav-item my-1 mx-1" style="time-tracker">
        <div class="attendence-box">
          <div class="card" style="width:7rem;height:5rem" >
            <div class="card-body">
              <div class="attendence-timer text-center">
                {% csrf_token %}
                <input type="hidden" id="hidden_attendence_timer" />
                <div id="timer" class="timer" style="font-size:16px">
                   00:00:00
                </div>
              </div>
              <div class="check-in-attendence-btn my-1">
                <button class="btn btn-success w-100 btn-sm" id="check-in-btn" onclick="javascript:check_in()" style="display:block;font-size:15px">Check-In</button>
                <button class="btn btn-danger w-100 btn-sm" id="check-out-btn" onclick="javascript:check_out()" style="display:none;
                font-size:15px">Check-Out</button>
              </div>
            </div>
          </div>         
        </div>
      </li>
      <a href="{% url 'zoho:home' %}" class="text-dark" style="text-decoration:none">
        <li class="nav-item my-1 mx-1" role="button" style="cursor:pointer">
          <div class="card" style="width:7rem;height:5rem">
            <div class="card-body">
              <div name="menu-icon" style="text-align:center">
                <i class="fa-solid fa-user"></i>
              </div>
              <div class="menu-name">
                <div class="text-center" style="font-size:14px">Home</div>
              </div>
            </div>
          </div>           
        </li>
      </a>

      <a href="{% url 'zoho:self' %}" class="text-dark" style="text-decoration:none">
         <li class="nav-item my-1 mx-1" role="button" style="cursor:pointer">
           <div class="card" style="width:7rem;height:5rem">
             <div class="card-body">
               <div name="menu-icon" style="text-align:center">
                 <i class="fa-solid fa-user"></i>
               </div>
               <div class="menu-name">
                 <div class="text-center" style="font-size:14px">Self Service</div>
               </div>
             </div>
           </div>           
         </li>
      </a>
      
      <li class="nav-item my-1 mx-1" style="cursor:pointer">
        <div class="card" style="width:7rem;height:5rem">
          <div class="card-body">
            <div name="menu-icon" style="text-align:center">
              <i class="fa-solid fa-graduation-cap"></i>
            </div>
            <div class="menu-name text-wrap">
              <div class="text-center" style="font-size:14px">Learning & Development</div>
            </div>
          </div>
        </div>
      </li>
      <a href="{% url 'zoho:leaver-tracker' %}" class="text-dark" style="text-decoration:none">
        <li class="nav-item my-1 mx-1" style="cursor:pointer">
          <div class="card" style="width:7rem;height:5rem">
            <div class="card-body">
              <div name="menu-icon" style="text-align:center">
                <i class="fa-solid fa-suitcase"></i>
              </div>
              <div class="menu-name">
                <div class="text-center" style="font-size:14px">Leave Tracker</div>
              </div>
            </div>
          </div>
        </li>
      </a>
      <a href="{% url 'zoho:time-tracker' %}"
      class="text-dark" style="text-decoration:none">
       <li class="nav-item my-1 mx-1" style="time-tracker">
         <div class="card" style="width:7rem;height:5rem">
           <div class="card-body">
             <div name="menu-icon" style="text-align:center">
               <i class="fa-solid fa-clock"></i>
             </div>
             <div class="menu-name">
               <div class="text-center" style="font-size:14px">Time Tracker</div>
             </div>
           </div>
         </div>
       </li>
      </a>

      <a href="{% url 'zoho:attendence-list-view' %}"
      class="text-dark" style="text-decoration:none">
       <li class="nav-item my-1 mx-1" style="time-tracker">
         <div class="card" style="width:7rem;height:5rem">
           <div class="card-body">
             <div name="menu-icon" style="text-align:center">
              <i class="fa-solid fa-clipboard-user"></i>
             </div>
             <div class="menu-name">
               <div class="text-center" style="font-size:14px">Attendence</div>
             </div>
           </div>
         </div>
       </li>
      </a>
      
     </ul>
   </div>
 </div>

zoho/clone/templates/time-tracker.html
{% include 'layout.html' %}
{% load static %}

{% block content %}


<div class="d-flex flex-column">
   <div class="row">
      <div class="col-2"> 
         {% include 'menu.html' %} 
      </div>
      <div class="col-10">
         <div class="daily-log-btn my-2">
            <a href="{% url 'zoho:daily-log' %}" role="button" class="form-control btn-primary text-center" style="width:15% !important;text-decoration:none">Add Daily Log</a>
         </div>
      </div>
   </div>
</div>

{% endblock content %}